spring:
  config:
    import: classpath:/yaml/
  profiles:
    group:
      logging-dev: dev, log
      logging-local: local, log
      logging-test: test, log
    active: ${SPRING_PROFILES_ACTIVE}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

resilience4j:
  circuitbreaker:
    instances:
      tosspayments:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
